const hotelData =[
    {
        "destinationId": 1,
        "id": 1,
        "name": "Light bright airy stylish apt & safe peaceful stay",
        "capacity":"4 guests   2 bedrooms   2 beds   2 baths",
        "description":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
        "rating":"4.9 (20)",
        "price":32,
        "image": "https://gdurl.com/FZIr",
        },
        {
            "destinationId": 1,
        "id": 2,
        "name": "Apartment in Lost Panorama",
        "capacity":"4 guests   2 bedrooms   2 beds   2 baths",
        "description":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
        "rating":"4.9 (20)",
        "price":32,
        "image":"https://gdurl.com/7ZoZ",
        },
        {
            "destinationId": 1,
        "id": 3,
        "name": "AR Lounge & Pool (r&r + b&b)",
        "capacity":"4 guests   2 bedrooms   2 beds   2 baths",
        "description":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
        "rating":"4.9 (20)",
        "price":32,
        "image":"https://gdurl.com/v9YR",
        },
        {
            "destinationId": 2,
        "id": 4,
        "name": "Light bright airy stylish apt & safe peaceful stay",
        "capacity":"4 guests   2 bedrooms   2 beds   2 baths",
        "description":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
        "rating":"4.9 (20)",
        "price":32,
        "image": "https://gdurl.com/FZIr",
        },
        {
            "destinationId": 2,
        "id": 5,
        "name": "AR Lounge & Pool (r&r + b&b)",
        "capacity":"4 guests   2 bedrooms   2 beds   2 baths",
        "description":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
        "rating":"4.9 (20)",
        "price":32,
        "image":"https://gdurl.com/v9YR",
        },
        {
            "destinationId": 2,
        "id": 6,
        "name": "Apartment in Lost Panorama",
        "capacity":"4 guests   2 bedrooms   2 beds   2 baths",
        "description":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
        "rating":"4.9 (20)",
        "price":32,
        "image":"https://gdurl.com/7ZoZ",
        
        },
        {
            "destinationId": 3,
        "id": 7,
        "name": "AR Lounge & Pool (r&r + b&b)",
        "capacity":"4 guests   2 bedrooms   2 beds   2 baths",
        "description":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
        "rating":"4.9 (20)",
        "price":32,
        "image":"https://gdurl.com/v9YR",
        
        },
        {
            "destinationId": 3,
        "id": 8,
        "name": "Apartment in Lost Panorama",
        "capacity":"4 guests   2 bedrooms   2 beds   2 baths",
        "description":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
        "rating":"4.9 (20)",
        "price":32,
        "image":"https://gdurl.com/7ZoZ",
        
        },
        {
            "destinationId": 3,
            "id": 9,
            "name": "Light bright airy stylish apt & safe peaceful stay",
            "capacity":"4 guests   2 bedrooms   2 beds   2 baths",
            "description":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
            "rating":"4.9 (20)",
            "price":32,
            "image": "https://gdurl.com/FZIr",
        
        }
]
export default hotelData;